route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: ${VOLUNTEERS_TELEGRAM__ALERT_TOKEN}
    chat_id: ${VOLUNTEERS_TELEGRAM__CHAT_ID}
    parse_mode: 'HTML'
    api_url: 'https://api.telegram.org'
    message: '{{ template "telegram.message" . }}'

templates:
- '/etc/alertmanager/templates/*.tmpl'