route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  telegram_configs:
  - bot_token: '{{ .Env.VOLUNTEERS_TELEGRAM__ALERT_TOKEN }}'
    chat_id: '{{ .Env.VOLUNTEERS_TELEGRAM__CHAT_ID }}'
    parse_mode: 'HTML'
    message: '{{ template "telegram.message" . }}'

templates:
- '/etc/alertmanager/template/*.tmpl'