"""add day scores

Revision ID: 6a74c54533d2
Revises: b756d8f01982
Create Date: 2025-10-25 21:03:54.206262

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a74c54533d2"
down_revision: str | None = "b756d8f01982"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("days", sa.Column("score", sa.Double(), nullable=True))
    op.add_column(
        "days", sa.Column("mandatory", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("days", "mandatory")
    op.drop_column("days", "score")
    # ### end Alembic commands ###
