"""add_needs_invitation_to_application_form

Revision ID: 56fe408ce2f9
Revises: 0f0ce454d3ce
Create Date: 2025-11-08 01:40:55.670815

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56fe408ce2f9"
down_revision: str | None = "0f0ce454d3ce"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_forms",
        sa.Column("needs_invitation", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_forms", "needs_invitation")
    # ### end Alembic commands ###
