"""split_full_name_en_into_first_and_last

Revision ID: eef28c0cd39e
Revises: 56fe408ce2f9
Create Date: 2025-11-08 02:03:21.093635

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eef28c0cd39e"
down_revision: str | None = "56fe408ce2f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add new columns as nullable first
    op.add_column("users", sa.Column("first_name_en", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name_en", sa.String(), nullable=True))

    # Step 2: Migrate data from full_name_en to first_name_en and last_name_en
    # Split full_name_en by space, taking first part as first_name and rest as last_name
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        UPDATE users
        SET
            first_name_en = CASE
                WHEN full_name_en IS NULL OR full_name_en = '' THEN ''
                WHEN position(' ' in full_name_en) > 0 THEN
                    substring(full_name_en from 1 for position(' ' in full_name_en) - 1)
                ELSE full_name_en
            END,
            last_name_en = CASE
                WHEN full_name_en IS NULL OR full_name_en = '' THEN ''
                WHEN position(' ' in full_name_en) > 0 THEN
                    substring(full_name_en from position(' ' in full_name_en) + 1)
                ELSE ''
            END
        WHERE first_name_en IS NULL OR last_name_en IS NULL
    """)
    )

    # Step 3: Make columns non-nullable
    op.alter_column("users", "first_name_en", nullable=False)
    op.alter_column("users", "last_name_en", nullable=False)

    # Step 4: Drop the old column
    op.drop_column("users", "full_name_en")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add full_name_en column as nullable first
    op.add_column("users", sa.Column("full_name_en", sa.VARCHAR(), nullable=True))

    # Step 2: Migrate data from first_name_en and last_name_en back to full_name_en
    connection = op.get_bind()
    connection.execute(
        sa.text("""
        UPDATE users
        SET full_name_en = TRIM(CONCAT(COALESCE(first_name_en, ''), ' ', COALESCE(last_name_en, '')))
    """)
    )

    # Step 3: Make column non-nullable
    op.alter_column("users", "full_name_en", nullable=False)

    # Step 4: Drop the new columns
    op.drop_column("users", "last_name_en")
    op.drop_column("users", "first_name_en")
    # ### end Alembic commands ###
