"""add_has_halls_flag_to_position

Revision ID: a795c5ed34a7
Revises: 834423efd9a6
Create Date: 2025-09-23 02:05:54.033903

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a795c5ed34a7"
down_revision: str | None = "834423efd9a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column("positions", sa.Column("has_halls", sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE positions SET has_halls = false WHERE has_halls IS NULL")
    # Make column not nullable
    op.alter_column("positions", "has_halls", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "has_halls")
    # ### end Alembic commands ###
