"""make telegram_id optionsl

Revision ID: d0b6e64e702c
Revises: 7af3bb8e3e94
Create Date: 2025-09-22 23:03:40.576858

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0b6e64e702c"
down_revision: str | None = "7af3bb8e3e94"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "telegram_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "telegram_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
