"""add_unique_constraint_to_user_day

Revision ID: 1c4cf493daca
Revises: a795c5ed34a7
Create Date: 2025-09-23 02:52:14.481293

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c4cf493daca"
down_revision: str | None = "a795c5ed34a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_user_day_application_form_day", "user_days", ["application_form_id", "day_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_day_application_form_day", "user_days", type_="unique")
    # ### end Alembic commands ###
