"""extra_experience

Revision ID: aeda0ee4365c
Revises: 4cfe8ccd192a
Create Date: 2025-12-07 21:27:53.302573

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aeda0ee4365c"
down_revision: str | None = "4cfe8ccd192a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EXTRA_EXPERIENCES = [
    "Pasha\tGilev\t2018\t1.0",
    "Pasha\tGilev\t2019\t0.75",
    "Yulia\tUsacheva\t2018\t0.4375",
    "Tina\tUstrafeeva\t2018\t0.3125",
    "Tina\tUstrafeeva\t2022\t7.0",
    "Marina\tKarlukova\t2021\t0.001",
    "Yury\tKamenev\t2023\t0.3",
    "Evgeniy\tFeder\t2018\t2.5",
    "Evgeniy\tFeder\t2021\t0.1",
    "Alex\tKasatkin\t2018\t0.5",
    "Konstantin\tBats\t2021\t0.001",
    "ivan\tmedvedev\t2023\t1.0",
    "Victoria\tNemolyaeva\t2024\t0.5",
    "Ildar\tGainanov\t2024\t0.75",
    "Kamil\tNotfullin\t2024\t1.0",
    "Veronika\tKorneeva\t2024\t1.4",
    "ivan\tmedvedev\t2024\t1.0",
    "Ekaterina\tKuleshova\t2024\t0.2",
    # some inconsistencies
    # "Anna\tKopeliovich\t2024\t2.86",
    # "Andrey\tPlotnikov\t2024\t1.86",
    # "Igor\tKolobov\t2024\t2.79",
    # "Aleksej\tLapenok\t2024\t3.29",
    # "Pasha\tGilev\t2024\t1.86",
    # "Ekaterina\tKuleshova\t2024\t2",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extra_experiences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_form_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Double(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_form_id"],
            ["application_forms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    for row in EXTRA_EXPERIENCES:
        first_name, last_name, year, value = row.split("\t")
        connection = op.get_bind()
        year_id = connection.execute(
            sa.text("SELECT id FROM years WHERE year_name = :year"), {"year": year}
        ).scalar()
        users = connection.execute(
            sa.text(
                "SELECT id FROM users WHERE first_name_en = :first_name AND last_name_en = :last_name"
            ),
            {"first_name": first_name, "last_name": last_name},
        ).scalars()
        for user in users:
            application_form_id = connection.execute(
                sa.text(
                    "SELECT id FROM application_forms WHERE year_id = :year_id AND user_id = :user_id"
                ),
                {"year_id": year_id, "user_id": user},
            ).scalar()
            if not application_form_id:
                continue
            connection.execute(
                sa.text(
                    "INSERT INTO extra_experiences (application_form_id, value) VALUES (:application_form_id, :value)"
                ),
                {"application_form_id": application_form_id, "value": float(value)},
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("extra_experiences")
    # ### end Alembic commands ###
