"""add_legacy_user

Revision ID: 7af3bb8e3e94
Revises: e0fc8f82a9af
Create Date: 2025-09-22 21:49:39.715859

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7af3bb8e3e94"
down_revision: str | None = "e0fc8f82a9af"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("new_user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["new_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("legacy_users")
    # ### end Alembic commands ###
