"""add_can_desire_to_positions

Revision ID: e0fc8f82a9af
Revises: 252ee2774277
Create Date: 2025-09-21 20:23:14.556810

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0fc8f82a9af"
down_revision: str | None = "ffef4006794c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("can_desire", sa.Boolean(), nullable=True))
    op.execute("UPDATE positions SET can_desire = false")
    op.alter_column("positions", "can_desire", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "can_desire")
    # ### end Alembic commands ###
