"""add assignment_published column

Revision ID: 0f0ce454d3ce
Revises: 6a74c54533d2
Create Date: 2025-10-26 22:47:12.372043

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f0ce454d3ce"
down_revision: str | None = "6a74c54533d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "days",
        sa.Column("assignment_published", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("days", "assignment_published")
    # ### end Alembic commands ###
