"""many updates

Revision ID: d8ff83645346
Revises: cd2a2b0b1b25
Create Date: 2025-12-07 02:40:07.695191

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d8ff83645346"
down_revision: str | None = "cd2a2b0b1b25"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("male", "female", "unspecified", name="gender_enum").create(op.get_bind())
    op.add_column(
        "positions", sa.Column("score", sa.Double(), server_default="1.0", nullable=False)
    )
    op.add_column(
        "positions",
        sa.Column("save_for_next_year", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("positions", sa.Column("description", sa.String(), nullable=True))
    op.drop_constraint("positions_name_key", "positions", type_="unique")
    op.add_column(
        "users",
        sa.Column(
            "gender",
            postgresql.ENUM("male", "female", "unspecified", name="gender_enum", create_type=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    op.create_unique_constraint(
        "positions_name_key", "positions", ["name"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("positions", "description")
    op.drop_column("positions", "save_for_next_year")
    op.drop_column("positions", "score")
    sa.Enum("male", "female", "unspecified", name="gender_enum").drop(op.get_bind())
    # ### end Alembic commands ###
