"""change_day_scores

Revision ID: 6b56be4bded7
Revises: aeda0ee4365c
Create Date: 2025-12-07 22:05:34.220963

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b56be4bded7"
down_revision: str | None = "aeda0ee4365c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

data = [
    "0.5\t2017-12-02. NEERC-Prev",
    "0.5\t2017-12-09. SCH-Prev",
    "0.5\t2018-12-01.NEERC-Prev",
    "0.5\t2018-12-08.SCH-Prev",
    "0.0\t2022-12-04.NERC-School-Registration",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE days
        SET score = 1
        """
    )
    for row in data:
        score, name = row.split("\t")
        op.execute(
            f"""
            UPDATE days
            SET score = {score}
            WHERE name = '{name}'
            """  # noqa: S608
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE days
        SET score = NULL
        """
    )
    # ### end Alembic commands ###
