"""Add phone, email, telegram_username fields to users table

Revision ID: ffef4006794c
Revises: 842a2bbaad5e
Create Date: 2025-09-06 16:23:35.245698

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffef4006794c"
down_revision: str | None = "842a2bbaad5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("users", sa.Column("email", sa.String(), nullable=True))
    op.add_column("users", sa.Column("telegram_username", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "telegram_username")
    op.drop_column("users", "email")
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
