"""wtf

Revision ID: c3462addaa0d
Revises: e64a68a01003
Create Date: 2025-05-17 23:31:36.472023

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c3462addaa0d"
down_revision: str | None = "e64a68a01003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("patronymic_ru", sa.String(), nullable=True))
    op.add_column("users", sa.Column("full_name_en", sa.String(), nullable=False))
    op.drop_constraint("users_phone_number_key", "users", type_="unique")
    op.drop_constraint("users_telegram_username_key", "users", type_="unique")
    op.drop_column("users", "first_name_en")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "telegram_username")
    op.drop_column("users", "last_name_en")
    op.add_column("years", sa.Column("year_name", sa.String(), nullable=False))
    op.add_column("years", sa.Column("open_for_registration", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("years", "open_for_registration")
    op.drop_column("years", "year_name")
    op.add_column(
        "users", sa.Column("last_name_en", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users", sa.Column("telegram_username", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users", sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "users", sa.Column("first_name_en", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("users_telegram_username_key", "users", ["telegram_username"])
    op.create_unique_constraint("users_phone_number_key", "users", ["phone_number"])
    op.drop_column("users", "full_name_en")
    op.drop_column("users", "patronymic_ru")
    # ### end Alembic commands ###
