"""add_hall_model_and_position_hall_to_userday

Revision ID: 834423efd9a6
Revises: d0b6e64e702c
Create Date: 2025-09-23 01:50:00.662517

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "834423efd9a6"
down_revision: str | None = "d0b6e64e702c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "halls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["year_id"],
            ["years.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user_days", sa.Column("position_id", sa.Integer(), nullable=True))
    op.add_column("user_days", sa.Column("hall_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_user_days_position_id", "user_days", "positions", ["position_id"], ["id"]
    )
    op.create_foreign_key("fk_user_days_hall_id", "user_days", "halls", ["hall_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_days_position_id", "user_days", type_="foreignkey")
    op.drop_constraint("fk_user_days_hall_id", "user_days", type_="foreignkey")
    op.drop_column("user_days", "hall_id")
    op.drop_column("user_days", "position_id")
    op.drop_table("halls")
    # ### end Alembic commands ###
