"""make_all_days_mandatory

Revision ID: 2351cfc2c2ee
Revises: 6b56be4bded7
Create Date: 2025-12-08 02:31:41.818360

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2351cfc2c2ee"
down_revision: str | None = "6b56be4bded7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE days
        SET mandatory = TRUE
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
