"""add user identities

Revision ID: 65685f86179a
Revises: 2351cfc2c2ee
Create Date: 2026-10-04 13:51:46.908388

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65685f86179a"
down_revision: str | None = "2351cfc2c2ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_identities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("telegram", "keycloak", "legacy", name="identity_provider_enum"),
            nullable=False,
        ),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("secret", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "subject", name="user_identities_unique_provider_subject"),
    )
    op.create_index(
        op.f("ix_user_identities_user_id"), "user_identities", ["user_id"], unique=False
    )
    # ### end Alembic commands ###

    # Move telegram logins and legacy accounts into identities
    op.execute(
        """
        INSERT INTO user_identities (user_id, provider, subject, display_name)
        SELECT id, 'telegram', telegram_id::text,
               CASE WHEN telegram_username IS NOT NULL THEN '@' || telegram_username END
        FROM users
        WHERE telegram_id IS NOT NULL
        """
    )
    op.execute(
        """
        INSERT INTO user_identities (user_id, provider, subject, display_name, secret)
        SELECT new_user_id, 'legacy', email, email, password
        FROM legacy_users
        ORDER BY id
        ON CONFLICT (provider, subject) DO NOTHING
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("legacy_users")
    op.drop_constraint("users_telegram_id_key", "users", type_="unique")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram_id", sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_unique_constraint(
        "users_telegram_id_key", "users", ["telegram_id"], postgresql_nulls_not_distinct=False
    )
    op.create_table(
        "legacy_users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("new_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["new_user_id"], ["users.id"], name="legacy_users_new_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="legacy_users_pkey"),
    )
    # ### end Alembic commands ###

    op.execute(
        """
        UPDATE users SET telegram_id = ui.subject::bigint
        FROM user_identities ui
        WHERE ui.user_id = users.id AND ui.provider = 'telegram'
        """
    )
    op.execute(
        """
        INSERT INTO legacy_users (new_user_id, email, password)
        SELECT user_id, subject, secret
        FROM user_identities
        WHERE provider = 'legacy'
        ORDER BY id
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_identities_user_id"), table_name="user_identities")
    op.drop_table("user_identities")
    # ### end Alembic commands ###
    sa.Enum(name="identity_provider_enum").drop(op.get_bind(), checkfirst=True)
