"""add unusual skills to application forms

Revision ID: d46f04d88e52
Revises: 2351cfc2c2ee
Create Date: 2026-09-08 22:19:10.821868

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd46f04d88e52'
down_revision: str | None = '2351cfc2c2ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('application_forms', sa.Column('unusual_skills', sa.String(), nullable=False))
#     # ### end Alembic commands ###

def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "application_forms",
        sa.Column(
            "unusual_skills",
            sa.String(),
            nullable=False,
            server_default="",
        ),
    )

    op.alter_column(
        "application_forms",
        "unusual_skills",
        server_default=None,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application_forms', 'unusual_skills')
    # ### end Alembic commands ###
