"""add additional skills to application forms

Revision ID: 0c9ac87df950
Revises: 2351cfc2c2ee
Create Date: 2026-10-04 14:04:02.676977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c9ac87df950"
down_revision: str | None = "2351cfc2c2ee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_forms",
        sa.Column("additional_skills", sa.String(), server_default="", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_forms", "additional_skills")
    # ### end Alembic commands ###
