---
rule_files:
  - '/etc/prometheus/prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Mac/Windows
      # For Linux use: ['172.17.0.1:8000'] or create a network

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
