rule_files:
  - '/etc/prometheus/prometheus.rules.yml'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'fastapi'
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['host.docker.internal:8000', 'host-gateway:8000', 'fastapi:8000']

alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
