// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { AddAssessmentApiV1AdminAssessmentAddPostData, AddAssessmentApiV1AdminAssessmentAddPostResponse, AddAssessmentApiV1AdminAssessmentAddPostError, EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostData, EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostError, AddDayApiV1AdminDayAddPostData, AddDayApiV1AdminDayAddPostResponse, AddDayApiV1AdminDayAddPostError, EditDayApiV1AdminDayDayIdEditPostData, EditDayApiV1AdminDayDayIdEditPostError, AddPositionApiV1AdminPositionAddPostData, AddPositionApiV1AdminPositionAddPostResponse, AddPositionApiV1AdminPositionAddPostError, EditPositionApiV1AdminPositionPositionIdEditPostData, EditPositionApiV1AdminPositionPositionIdEditPostError, AddUserDayApiV1AdminUserDayAddPostData, AddUserDayApiV1AdminUserDayAddPostResponse, AddUserDayApiV1AdminUserDayAddPostError, EditPositionApiV1AdminUserDayUserDayIdEditPostData, EditPositionApiV1AdminUserDayUserDayIdEditPostError, AddYearApiV1AdminYearAddPostData, AddYearApiV1AdminYearAddPostResponse, AddYearApiV1AdminYearAddPostError, EditYearApiV1AdminYearYearIdEditPostData, EditYearApiV1AdminYearYearIdEditPostError, RegisterApiV1AuthTelegramRegisterPostData, RegisterApiV1AuthTelegramRegisterPostResponse, RegisterApiV1AuthTelegramRegisterPostError, LoginApiV1AuthTelegramLoginPostData, LoginApiV1AuthTelegramLoginPostResponse, LoginApiV1AuthTelegramLoginPostError, RefreshApiV1AuthRefreshPostData, RefreshApiV1AuthRefreshPostResponse, RefreshApiV1AuthRefreshPostError, MeApiV1AuthMeGetData, MeApiV1AuthMeGetResponse, UpdateUserApiV1AuthUpdatePostData, UpdateUserApiV1AuthUpdatePostResponse, UpdateUserApiV1AuthUpdatePostError, GetYearsApiV1YearGetData, GetYearsApiV1YearGetResponse, GetFormYearApiV1YearYearIdGetData, GetFormYearApiV1YearYearIdGetResponse, GetFormYearApiV1YearYearIdGetError, SaveFormYearApiV1YearYearIdPostData, SaveFormYearApiV1YearYearIdPostResponse, SaveFormYearApiV1YearYearIdPostError, ProxyPathGetData, ProxyPathGetError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Add Assessment
 * Add new assessment
 */
export const addAssessmentApiV1AdminAssessmentAddPost = <ThrowOnError extends boolean = false>(options: Options<AddAssessmentApiV1AdminAssessmentAddPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddAssessmentApiV1AdminAssessmentAddPostResponse, AddAssessmentApiV1AdminAssessmentAddPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/assessment/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Edit Assessment
 */
export const editAssessmentApiV1AdminAssessmentAssessmentIdEditPost = <ThrowOnError extends boolean = false>(options: Options<EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/assessment/{assessment_id}/edit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Add Day
 * Add new day
 */
export const addDayApiV1AdminDayAddPost = <ThrowOnError extends boolean = false>(options: Options<AddDayApiV1AdminDayAddPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddDayApiV1AdminDayAddPostResponse, AddDayApiV1AdminDayAddPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/day/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Edit Day
 */
export const editDayApiV1AdminDayDayIdEditPost = <ThrowOnError extends boolean = false>(options: Options<EditDayApiV1AdminDayDayIdEditPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, EditDayApiV1AdminDayDayIdEditPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/day/{day_id}/edit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Add Position
 * Add new position
 */
export const addPositionApiV1AdminPositionAddPost = <ThrowOnError extends boolean = false>(options: Options<AddPositionApiV1AdminPositionAddPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddPositionApiV1AdminPositionAddPostResponse, AddPositionApiV1AdminPositionAddPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/position/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Edit Position
 */
export const editPositionApiV1AdminPositionPositionIdEditPost = <ThrowOnError extends boolean = false>(options: Options<EditPositionApiV1AdminPositionPositionIdEditPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, EditPositionApiV1AdminPositionPositionIdEditPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/position/{position_id}/edit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Add User Day
 * Add new user day
 */
export const addUserDayApiV1AdminUserDayAddPost = <ThrowOnError extends boolean = false>(options: Options<AddUserDayApiV1AdminUserDayAddPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddUserDayApiV1AdminUserDayAddPostResponse, AddUserDayApiV1AdminUserDayAddPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/user-day/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Edit Position
 */
export const editPositionApiV1AdminUserDayUserDayIdEditPost = <ThrowOnError extends boolean = false>(options: Options<EditPositionApiV1AdminUserDayUserDayIdEditPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, EditPositionApiV1AdminUserDayUserDayIdEditPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/user-day/{user_day_id}/edit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Add Year
 * Add new year
 */
export const addYearApiV1AdminYearAddPost = <ThrowOnError extends boolean = false>(options: Options<AddYearApiV1AdminYearAddPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AddYearApiV1AdminYearAddPostResponse, AddYearApiV1AdminYearAddPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/year/add',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Edit Year
 */
export const editYearApiV1AdminYearYearIdEditPost = <ThrowOnError extends boolean = false>(options: Options<EditYearApiV1AdminYearYearIdEditPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, EditYearApiV1AdminYearYearIdEditPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/admin/year/{year_id}/edit',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Register
 */
export const registerApiV1AuthTelegramRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiV1AuthTelegramRegisterPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterApiV1AuthTelegramRegisterPostResponse, RegisterApiV1AuthTelegramRegisterPostError, ThrowOnError>({
        url: '/api/v1/auth/telegram/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Login
 */
export const loginApiV1AuthTelegramLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthTelegramLoginPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginApiV1AuthTelegramLoginPostResponse, LoginApiV1AuthTelegramLoginPostError, ThrowOnError>({
        url: '/api/v1/auth/telegram/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Refresh
 */
export const refreshApiV1AuthRefreshPost = <ThrowOnError extends boolean = false>(options: Options<RefreshApiV1AuthRefreshPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RefreshApiV1AuthRefreshPostResponse, RefreshApiV1AuthRefreshPostError, ThrowOnError>({
        url: '/api/v1/auth/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Me
 */
export const meApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<MeApiV1AuthMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<MeApiV1AuthMeGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/auth/me',
        ...options
    });
};

/**
 * Update User
 */
export const updateUserApiV1AuthUpdatePost = <ThrowOnError extends boolean = false>(options: Options<UpdateUserApiV1AuthUpdatePostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UpdateUserApiV1AuthUpdatePostResponse, UpdateUserApiV1AuthUpdatePostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/auth/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Get Years
 * Return info about all years
 */
export const getYearsApiV1YearGet = <ThrowOnError extends boolean = false>(options?: Options<GetYearsApiV1YearGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetYearsApiV1YearGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/year/',
        ...options
    });
};

/**
 * Get Form Year
 * Return year positions, days and saved user form data
 */
export const getFormYearApiV1YearYearIdGet = <ThrowOnError extends boolean = false>(options: Options<GetFormYearApiV1YearYearIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetFormYearApiV1YearYearIdGetResponse, GetFormYearApiV1YearYearIdGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/year/{year_id}',
        ...options
    });
};

/**
 * Save Form Year
 * Save user year form data
 */
export const saveFormYearApiV1YearYearIdPost = <ThrowOnError extends boolean = false>(options: Options<SaveFormYearApiV1YearYearIdPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SaveFormYearApiV1YearYearIdPostResponse, SaveFormYearApiV1YearYearIdPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/year/{year_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Proxy
 */
export const proxyPathGet = <ThrowOnError extends boolean = false>(options: Options<ProxyPathGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ProxyPathGetError, ThrowOnError>({
        url: '/{path}',
        ...options
    });
};
