// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-axios';
import type { RegisterApiV1AuthTelegramRegisterPostData, RegisterApiV1AuthTelegramRegisterPostResponse, RegisterApiV1AuthTelegramRegisterPostError, LoginApiV1AuthTelegramLoginPostData, LoginApiV1AuthTelegramLoginPostResponse, LoginApiV1AuthTelegramLoginPostError, RefreshApiV1AuthRefreshPostData, RefreshApiV1AuthRefreshPostResponse, RefreshApiV1AuthRefreshPostError, MeApiV1AuthMeGetData, MeApiV1AuthMeGetResponse, GetYearsApiV1YearGetData, GetYearsApiV1YearGetResponse, GetFormYearApiV1YearYearIdGetData, GetFormYearApiV1YearYearIdGetResponse, GetFormYearApiV1YearYearIdGetError, SaveFormYearApiV1YearYearIdPostData, SaveFormYearApiV1YearYearIdPostResponse, SaveFormYearApiV1YearYearIdPostError, ProxyPathGetData, ProxyPathGetError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register
 */
export const registerApiV1AuthTelegramRegisterPost = <ThrowOnError extends boolean = false>(options: Options<RegisterApiV1AuthTelegramRegisterPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RegisterApiV1AuthTelegramRegisterPostResponse, RegisterApiV1AuthTelegramRegisterPostError, ThrowOnError>({
        url: '/api/v1/auth/telegram/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Login
 */
export const loginApiV1AuthTelegramLoginPost = <ThrowOnError extends boolean = false>(options: Options<LoginApiV1AuthTelegramLoginPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginApiV1AuthTelegramLoginPostResponse, LoginApiV1AuthTelegramLoginPostError, ThrowOnError>({
        url: '/api/v1/auth/telegram/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Refresh
 */
export const refreshApiV1AuthRefreshPost = <ThrowOnError extends boolean = false>(options: Options<RefreshApiV1AuthRefreshPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RefreshApiV1AuthRefreshPostResponse, RefreshApiV1AuthRefreshPostError, ThrowOnError>({
        url: '/api/v1/auth/refresh',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Me
 */
export const meApiV1AuthMeGet = <ThrowOnError extends boolean = false>(options?: Options<MeApiV1AuthMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<MeApiV1AuthMeGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/auth/me',
        ...options
    });
};

/**
 * Get Years
 * Return info about all years
 */
export const getYearsApiV1YearGet = <ThrowOnError extends boolean = false>(options?: Options<GetYearsApiV1YearGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetYearsApiV1YearGetResponse, unknown, ThrowOnError>({
        url: '/api/v1/year/',
        ...options
    });
};

/**
 * Get Form Year
 * Return year positions and saved user form data
 */
export const getFormYearApiV1YearYearIdGet = <ThrowOnError extends boolean = false>(options: Options<GetFormYearApiV1YearYearIdGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetFormYearApiV1YearYearIdGetResponse, GetFormYearApiV1YearYearIdGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/year/{year_id}',
        ...options
    });
};

/**
 * Save Form Year
 * Save user year form data
 */
export const saveFormYearApiV1YearYearIdPost = <ThrowOnError extends boolean = false>(options: Options<SaveFormYearApiV1YearYearIdPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<SaveFormYearApiV1YearYearIdPostResponse, SaveFormYearApiV1YearYearIdPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/api/v1/year/{year_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Proxy
 */
export const proxyPathGet = <ThrowOnError extends boolean = false>(options: Options<ProxyPathGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<unknown, ProxyPathGetError, ThrowOnError>({
        url: '/{path}',
        ...options
    });
};
