// This file is auto-generated by @hey-api/openapi-ts

export type AddAssessmentRequest = {
    user_day_id: number;
    comment: string;
    value: number;
};

export type AddAssessmentResponse = {
    success?: true;
    assessment_id: number;
};

export type AddDayRequest = {
    year_id: number;
    name: string;
    information: string;
};

export type AddDayResponse = {
    success?: true;
    day_id: number;
};

export type AddPositionRequest = {
    year_id: number;
    name: string;
};

export type AddPositionResponse = {
    success?: true;
    position_id: number;
};

export type AddUserDayRequest = {
    application_form_id: number;
    day_id: number;
    information: string;
    attendance?: Attendance;
};

export type AddUserDayResponse = {
    success?: true;
    user_day_id: number;
};

export type AddYearRequest = {
    year_name: string;
};

export type AddYearResponse = {
    success?: true;
    year_id: number;
};

export type ApplicationFormYearSaveRequest = {
    desired_positions_ids: Array<number>;
    itmo_group?: string | null;
    comments?: string;
};

export type ApplicationFormYearSavedResponse = {
    success?: true;
    positions: Array<PositionOut>;
    days: Array<DayOut>;
    desired_positions: Array<PositionOut>;
    itmo_group?: string | null;
    comments?: string;
};

export type Attendance = 'yes' | 'no' | 'late' | 'sick' | 'unknown';

export type DayOut = {
    year_id: number;
    name: string;
    information: string;
    day_id: number;
};

export type EditAssessmentRequest = {
    comment?: string | null;
    value?: number | null;
};

export type EditDayRequest = {
    name?: string | null;
    information?: string | null;
};

export type EditPositionRequest = {
    name?: string | null;
};

export type EditUserDayRequest = {
    information?: string | null;
    attendance?: Attendance | null;
};

export type EditYearRequest = {
    year_name?: string | null;
    open_for_registration?: boolean | null;
};

export type ErrorLoginResponse = {
    success?: false;
    description: string;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type PositionOut = {
    year_id: number;
    name: string;
    position_id: number;
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type RegistrationRequest = {
    telegram_id: number;
    telegram_auth_date: number;
    telegram_first_name: string;
    telegram_hash: string;
    telegram_last_name?: string | null;
    telegram_username?: string | null;
    telegram_photo_url?: string | null;
    first_name_ru: string;
    last_name_ru: string;
    full_name_en: string;
    isu_id?: number | null;
    patronymic_ru?: string | null;
};

export type SuccessfulLoginResponse = {
    success?: true;
    token: string;
    refresh_token: string;
    expires_in: number;
    refresh_expires_in: number;
};

export type TelegramLoginRequest = {
    telegram_id: number;
    telegram_auth_date: number;
    telegram_first_name: string;
    telegram_hash: string;
    telegram_last_name?: string | null;
    telegram_username?: string | null;
    telegram_photo_url?: string | null;
};

export type UserResponse = {
    user_id: number;
    first_name_ru: string;
    last_name_ru: string;
    full_name_en: string;
    is_admin: boolean;
    isu_id: number | null;
    patronymic_ru: string | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type YearOut = {
    year_name: string;
    open_for_registration: boolean;
    year_id: number;
};

export type YearsResponse = {
    success?: true;
    years: Array<YearOut>;
};

export type AddAssessmentApiV1AdminAssessmentAddPostData = {
    body: AddAssessmentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/assessment/add';
};

export type AddAssessmentApiV1AdminAssessmentAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddAssessmentApiV1AdminAssessmentAddPostError = AddAssessmentApiV1AdminAssessmentAddPostErrors[keyof AddAssessmentApiV1AdminAssessmentAddPostErrors];

export type AddAssessmentApiV1AdminAssessmentAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddAssessmentResponse;
    /**
     * Returned when assessment successfully added
     */
    201: unknown;
};

export type AddAssessmentApiV1AdminAssessmentAddPostResponse = AddAssessmentApiV1AdminAssessmentAddPostResponses[keyof AddAssessmentApiV1AdminAssessmentAddPostResponses];

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostData = {
    body: EditAssessmentRequest;
    path: {
        assessment_id: number;
    };
    query?: never;
    url: '/api/v1/admin/assessment/{assessment_id}/edit';
};

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostError = EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostErrors[keyof EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostErrors];

export type EditAssessmentApiV1AdminAssessmentAssessmentIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddDayApiV1AdminDayAddPostData = {
    body: AddDayRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/day/add';
};

export type AddDayApiV1AdminDayAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddDayApiV1AdminDayAddPostError = AddDayApiV1AdminDayAddPostErrors[keyof AddDayApiV1AdminDayAddPostErrors];

export type AddDayApiV1AdminDayAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddDayResponse;
    /**
     * Returned when day successfully added
     */
    201: unknown;
};

export type AddDayApiV1AdminDayAddPostResponse = AddDayApiV1AdminDayAddPostResponses[keyof AddDayApiV1AdminDayAddPostResponses];

export type EditDayApiV1AdminDayDayIdEditPostData = {
    body: EditDayRequest;
    path: {
        day_id: number;
    };
    query?: never;
    url: '/api/v1/admin/day/{day_id}/edit';
};

export type EditDayApiV1AdminDayDayIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditDayApiV1AdminDayDayIdEditPostError = EditDayApiV1AdminDayDayIdEditPostErrors[keyof EditDayApiV1AdminDayDayIdEditPostErrors];

export type EditDayApiV1AdminDayDayIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddPositionApiV1AdminPositionAddPostData = {
    body: AddPositionRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/position/add';
};

export type AddPositionApiV1AdminPositionAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddPositionApiV1AdminPositionAddPostError = AddPositionApiV1AdminPositionAddPostErrors[keyof AddPositionApiV1AdminPositionAddPostErrors];

export type AddPositionApiV1AdminPositionAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddPositionResponse;
    /**
     * Returned when position successfully added
     */
    201: unknown;
};

export type AddPositionApiV1AdminPositionAddPostResponse = AddPositionApiV1AdminPositionAddPostResponses[keyof AddPositionApiV1AdminPositionAddPostResponses];

export type EditPositionApiV1AdminPositionPositionIdEditPostData = {
    body: EditPositionRequest;
    path: {
        position_id: number;
    };
    query?: never;
    url: '/api/v1/admin/position/{position_id}/edit';
};

export type EditPositionApiV1AdminPositionPositionIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditPositionApiV1AdminPositionPositionIdEditPostError = EditPositionApiV1AdminPositionPositionIdEditPostErrors[keyof EditPositionApiV1AdminPositionPositionIdEditPostErrors];

export type EditPositionApiV1AdminPositionPositionIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddUserDayApiV1AdminUserDayAddPostData = {
    body: AddUserDayRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/user-day/add';
};

export type AddUserDayApiV1AdminUserDayAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddUserDayApiV1AdminUserDayAddPostError = AddUserDayApiV1AdminUserDayAddPostErrors[keyof AddUserDayApiV1AdminUserDayAddPostErrors];

export type AddUserDayApiV1AdminUserDayAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddUserDayResponse;
    /**
     * Returned when user day successfully added
     */
    201: unknown;
};

export type AddUserDayApiV1AdminUserDayAddPostResponse = AddUserDayApiV1AdminUserDayAddPostResponses[keyof AddUserDayApiV1AdminUserDayAddPostResponses];

export type EditPositionApiV1AdminUserDayUserDayIdEditPostData = {
    body: EditUserDayRequest;
    path: {
        user_day_id: number;
    };
    query?: never;
    url: '/api/v1/admin/user-day/{user_day_id}/edit';
};

export type EditPositionApiV1AdminUserDayUserDayIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditPositionApiV1AdminUserDayUserDayIdEditPostError = EditPositionApiV1AdminUserDayUserDayIdEditPostErrors[keyof EditPositionApiV1AdminUserDayUserDayIdEditPostErrors];

export type EditPositionApiV1AdminUserDayUserDayIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AddYearApiV1AdminYearAddPostData = {
    body: AddYearRequest;
    path?: never;
    query?: never;
    url: '/api/v1/admin/year/add';
};

export type AddYearApiV1AdminYearAddPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AddYearApiV1AdminYearAddPostError = AddYearApiV1AdminYearAddPostErrors[keyof AddYearApiV1AdminYearAddPostErrors];

export type AddYearApiV1AdminYearAddPostResponses = {
    /**
     * Successful Response
     */
    200: AddYearResponse;
    /**
     * Returned when year successfully added
     */
    201: unknown;
};

export type AddYearApiV1AdminYearAddPostResponse = AddYearApiV1AdminYearAddPostResponses[keyof AddYearApiV1AdminYearAddPostResponses];

export type EditYearApiV1AdminYearYearIdEditPostData = {
    body: EditYearRequest;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/admin/year/{year_id}/edit';
};

export type EditYearApiV1AdminYearYearIdEditPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditYearApiV1AdminYearYearIdEditPostError = EditYearApiV1AdminYearYearIdEditPostErrors[keyof EditYearApiV1AdminYearYearIdEditPostErrors];

export type EditYearApiV1AdminYearYearIdEditPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterApiV1AuthTelegramRegisterPostData = {
    body: RegistrationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/telegram/register';
};

export type RegisterApiV1AuthTelegramRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterApiV1AuthTelegramRegisterPostError = RegisterApiV1AuthTelegramRegisterPostErrors[keyof RegisterApiV1AuthTelegramRegisterPostErrors];

export type RegisterApiV1AuthTelegramRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessfulLoginResponse;
};

export type RegisterApiV1AuthTelegramRegisterPostResponse = RegisterApiV1AuthTelegramRegisterPostResponses[keyof RegisterApiV1AuthTelegramRegisterPostResponses];

export type LoginApiV1AuthTelegramLoginPostData = {
    body: TelegramLoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/telegram/login';
};

export type LoginApiV1AuthTelegramLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginApiV1AuthTelegramLoginPostError = LoginApiV1AuthTelegramLoginPostErrors[keyof LoginApiV1AuthTelegramLoginPostErrors];

export type LoginApiV1AuthTelegramLoginPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessfulLoginResponse | ErrorLoginResponse;
};

export type LoginApiV1AuthTelegramLoginPostResponse = LoginApiV1AuthTelegramLoginPostResponses[keyof LoginApiV1AuthTelegramLoginPostResponses];

export type RefreshApiV1AuthRefreshPostData = {
    body: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/refresh';
};

export type RefreshApiV1AuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshApiV1AuthRefreshPostError = RefreshApiV1AuthRefreshPostErrors[keyof RefreshApiV1AuthRefreshPostErrors];

export type RefreshApiV1AuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: SuccessfulLoginResponse | ErrorLoginResponse;
};

export type RefreshApiV1AuthRefreshPostResponse = RefreshApiV1AuthRefreshPostResponses[keyof RefreshApiV1AuthRefreshPostResponses];

export type MeApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type MeApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type MeApiV1AuthMeGetResponse = MeApiV1AuthMeGetResponses[keyof MeApiV1AuthMeGetResponses];

export type GetYearsApiV1YearGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/year/';
};

export type GetYearsApiV1YearGetResponses = {
    /**
     * Successful Response
     */
    200: YearsResponse;
};

export type GetYearsApiV1YearGetResponse = GetYearsApiV1YearGetResponses[keyof GetYearsApiV1YearGetResponses];

export type GetFormYearApiV1YearYearIdGetData = {
    body?: never;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/year/{year_id}';
};

export type GetFormYearApiV1YearYearIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFormYearApiV1YearYearIdGetError = GetFormYearApiV1YearYearIdGetErrors[keyof GetFormYearApiV1YearYearIdGetErrors];

export type GetFormYearApiV1YearYearIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApplicationFormYearSavedResponse;
};

export type GetFormYearApiV1YearYearIdGetResponse = GetFormYearApiV1YearYearIdGetResponses[keyof GetFormYearApiV1YearYearIdGetResponses];

export type SaveFormYearApiV1YearYearIdPostData = {
    body: ApplicationFormYearSaveRequest;
    path: {
        year_id: number;
    };
    query?: never;
    url: '/api/v1/year/{year_id}';
};

export type SaveFormYearApiV1YearYearIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveFormYearApiV1YearYearIdPostError = SaveFormYearApiV1YearYearIdPostErrors[keyof SaveFormYearApiV1YearYearIdPostErrors];

export type SaveFormYearApiV1YearYearIdPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
    /**
     * Returned when user signed up form for the first time
     */
    201: unknown;
    /**
     * Returned when user updated form
     */
    204: void;
};

export type SaveFormYearApiV1YearYearIdPostResponse = SaveFormYearApiV1YearYearIdPostResponses[keyof SaveFormYearApiV1YearYearIdPostResponses];

export type ProxyPathGetData = {
    body?: never;
    path: {
        path: string;
    };
    query?: never;
    url: '/{path}';
};

export type ProxyPathGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProxyPathGetError = ProxyPathGetErrors[keyof ProxyPathGetErrors];

export type ProxyPathGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};
